import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 pb-16 min-h-screen">
        <div className="max-w-3xl mx-auto px-6">
          <h1 className="font-heading text-3xl md:text-4xl font-bold mb-8">Terms of Service</h1>
          <div className="prose prose-invert prose-zinc max-w-none text-zinc-400 space-y-6">
            <p className="text-sm text-zinc-500">Last updated: February 2026</p>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using ProposalPilot (&quot;the Service&quot;), operated by Automatik.studio,
                you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">2. Description of Service</h2>
              <p>
                ProposalPilot is an AI-powered tool that generates project proposals based on user-provided
                project descriptions. The Service uses artificial intelligence to create proposal drafts that
                users can customize, copy, and send to their clients.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">3. User Responsibilities</h2>
              <ul className="list-disc list-inside space-y-1 text-zinc-400">
                <li>You are responsible for reviewing and customizing generated proposals before sending them to clients</li>
                <li>You must not use the Service for fraudulent, misleading, or illegal purposes</li>
                <li>Generated content is a starting point — you are responsible for its accuracy and appropriateness</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">4. Intellectual Property</h2>
              <p>
                Proposals generated by ProposalPilot are yours to use as you see fit. You retain full ownership
                of the output. The ProposalPilot brand, logo, and website design remain the property of Automatik.studio.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">5. Limitation of Liability</h2>
              <p>
                ProposalPilot is provided &quot;as is&quot; without warranties of any kind. We are not responsible for the
                outcome of proposals sent to clients, lost deals, or any damages arising from the use of
                AI-generated content. Always review proposals before sending.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">6. Pricing & Billing</h2>
              <p>
                Free tier users receive a limited number of proposals per month. Paid plans, when available,
                will be billed monthly. Prices are subject to change with 30 days notice.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">7. Modifications</h2>
              <p>
                We reserve the right to modify these terms at any time. Changes will be posted on this page
                with an updated date. Continued use of the Service constitutes acceptance of the modified terms.
              </p>
            </section>

            <section>
              <h2 className="font-heading text-xl font-semibold text-zinc-200 mb-3">8. Contact</h2>
              <p>
                Questions about these terms? Contact us at{" "}
                <a href="mailto:automatikstudiomail@gmail.com" className="text-brand-amber hover:underline">
                  automatikstudiomail@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
